services:
  db:
    container_name: db
    image: postgres:16
    platform: linux/amd64
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5050:5050"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pnpm install && pnpm db:migrate && pnpm dev"

volumes:
  pgdata: